// <auto-generated/> by Diplomat

#pragma warning disable 0105
using System;
using System.Runtime.InteropServices;

{%- for using in config.usings %}
    using {{ using }};
{% endfor %}
using {{ config.namespace }}.Diplomat;
#pragma warning restore 0105

#nullable enable
