[package]
name = "diplomat"
version = "0.1.0"
authors = ["Shadaj Laddad <shadaj@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
diplomat_core = { path = "../core" }
syn = { version = "1.0", features = [ "full", "extra-traits" ] }
quote = "1.0"
